@echo off
REM ESMS - Supabase Setup Helper
REM This script guides you through Supabase setup

color 0A
echo ========================================
echo   ESMS - Supabase Setup Wizard
echo ========================================
echo.

echo This wizard will help you set up Supabase for ESMS.
echo.
echo STEP 1: Create Supabase Project
echo ================================
echo.
echo I will open Supabase in your browser.
echo.
echo Please:
echo   1. Sign in to Supabase (or create account)
echo   2. Click "New Project"
echo   3. Name it "ESMS"
echo   4. Choose a database password (SAVE IT!)
echo   5. Wait for project creation (1-2 minutes)
echo.
pause

REM Open Supabase
start https://supabase.com/dashboard

echo.
echo ========================================
echo STEP 2: Get Your API Keys
echo ========================================
echo.
echo In Supabase dashboard:
echo   1. Click Settings (gear icon) in left sidebar
echo   2. Click "API" in settings menu
echo   3. You'll see your credentials
echo.
echo Press any key when you're ready to continue...
pause >nul

echo.
echo ========================================
echo STEP 3: Copy Your Credentials
echo ========================================
echo.
echo You need to copy 3 values:
echo.
echo 1. PROJECT URL
echo    Example: https://xxxxxxxxxxxxx.supabase.co
echo.
set /p SUPABASE_URL="Paste your Project URL here: "

echo.
echo 2. ANON PUBLIC KEY
echo    (Long string starting with eyJ...)
echo.
set /p ANON_KEY="Paste your anon public key here: "

echo.
echo 3. SERVICE ROLE KEY
echo    (Click 'Reveal' button first, then copy)
echo.
set /p SERVICE_KEY="Paste your service_role key here: "

echo.
echo ========================================
echo STEP 4: Updating .env.local
echo ========================================
echo.

REM Create .env.local with the provided values
(
echo # Supabase Configuration
echo # Generated by setup-supabase.bat on %date% %time%
echo NEXT_PUBLIC_SUPABASE_URL=%SUPABASE_URL%
echo NEXT_PUBLIC_SUPABASE_ANON_KEY=%ANON_KEY%
echo SUPABASE_SERVICE_ROLE_KEY=%SERVICE_KEY%
echo.
echo # Application Configuration
echo NEXT_PUBLIC_APP_URL=http://localhost:3010
) > .env.local

echo [SUCCESS] .env.local file updated!
echo.

echo ========================================
echo STEP 5: Run Database Migrations
echo ========================================
echo.
echo Now you need to run SQL migrations in Supabase.
echo.
echo I will open:
echo   1. Supabase SQL Editor
echo   2. Migration file 1 in Notepad
echo   3. Migration file 2 in Notepad
echo.
echo Then you need to:
echo   1. Copy content from migration file 1
echo   2. Paste in SQL Editor and click RUN
echo   3. Copy content from migration file 2
echo   4. Paste in SQL Editor and click RUN
echo.
pause

REM Open SQL Editor
start %SUPABASE_URL%/project/_/sql

REM Wait a moment
timeout /t 2 /nobreak >nul

REM Open migration files in notepad
start notepad "supabase\migrations\001_initial_schema.sql"
timeout /t 1 /nobreak >nul
start notepad "supabase\migrations\002_rls_policies.sql"

echo.
echo ========================================
echo STEP 6: Verify Setup
echo ========================================
echo.
echo After running both migrations:
echo   1. Go to Table Editor in Supabase
echo   2. You should see 6 tables:
echo      - staff
echo      - rooms
echo      - exam_sessions
echo      - assignments
echo      - system_settings
echo      - audit_log
echo.
echo Press any key when migrations are complete...
pause >nul

echo.
echo ========================================
echo STEP 7: Test Connection
echo ========================================
echo.
echo Starting the development server to test...
echo.
pause

REM Start the app
call start-app.bat

echo.
echo ========================================
echo Setup Complete!
echo ========================================
echo.
echo If the app loads without errors, setup is successful!
echo.
echo Next steps:
echo   - Add sample data in Supabase Table Editor
echo   - See SUPABASE_SETUP.md for detailed guide
echo.
pause

